#!/bin/sh
# Xcode Cloud post-clone — runs once per build, immediately after Apple's
# VM clones the repo and before xcodebuild starts.
#
# Aether's `Aether.xcodeproj` is generated by XcodeGen from `project.yml`
# and intentionally not checked in. Xcode Cloud therefore needs to install
# XcodeGen and regenerate the project before the build can find a scheme.
#
# Reference:
#   https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -eu

echo "ci_post_clone: installing XcodeGen"
brew install xcodegen

# CI_PRIMARY_REPOSITORY_PATH is the canonical workspace root in Xcode Cloud.
# Fall back to CI_WORKSPACE for older runners and to the current directory
# for local invocation (handy for dry-run testing).
WORKSPACE="${CI_PRIMARY_REPOSITORY_PATH:-${CI_WORKSPACE:-$PWD}}"
cd "$WORKSPACE"

echo "ci_post_clone: running xcodegen generate in $WORKSPACE"
xcodegen generate

echo "ci_post_clone: done"
