#!/bin/sh
# Xcode Cloud post-clone — runs once per build, immediately after Apple's
# VM clones the repo and before xcodebuild starts.
#
# Aether's `Aether.xcodeproj` is generated by XcodeGen from `project.yml`
# and intentionally not checked in. Xcode Cloud therefore needs XcodeGen on
# the runner and must regenerate the project before the build can find a
# scheme.
#
# We install XcodeGen by downloading a pinned prebuilt release straight from
# GitHub — deliberately NOT `brew install xcodegen`. Homebrew runs an
# auto-update that fetches portable-ruby (and bottles) from `ghcr.io`; when
# that host isn't resolvable in the Xcode Cloud build network the auto-update
# fails and, under `set -e`, takes the whole build down before XcodeGen is
# ever installed:
#
#   curl: (6) Could not resolve host: ghcr.io
#   Error: Failed to upgrade Homebrew Portable Ruby!
#
# The GitHub release download avoids Homebrew and ghcr.io entirely. A Homebrew
# install (with auto-update disabled) remains as a last-ditch fallback.
#
# Reference:
#   https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -eu

# Pinned for reproducible CI. Bump deliberately; verify the tag's `xcodegen.zip`
# asset exists at github.com/yonaskolb/XcodeGen/releases.
XCODEGEN_VERSION="2.45.4"

WORKSPACE="${CI_PRIMARY_REPOSITORY_PATH:-${CI_WORKSPACE:-$PWD}}"
INSTALL_DIR="$(mktemp -d)"

echo "ci_post_clone: installing XcodeGen $XCODEGEN_VERSION from GitHub release"
if curl -fsSL \
    "https://github.com/yonaskolb/XcodeGen/releases/download/${XCODEGEN_VERSION}/xcodegen.zip" \
    -o "$INSTALL_DIR/xcodegen.zip"; then
  unzip -q -o "$INSTALL_DIR/xcodegen.zip" -d "$INSTALL_DIR"
  # The release unzips to `xcodegen/bin/xcodegen` with a sibling `share/`;
  # find it regardless of the exact layout and run it in place so it resolves
  # its bundled resources.
  XCODEGEN="$(find "$INSTALL_DIR" -type f -name xcodegen -path '*/bin/*' | head -1)"
  chmod +x "$XCODEGEN"
else
  echo "ci_post_clone: GitHub download failed; falling back to Homebrew (auto-update disabled)"
  export HOMEBREW_NO_AUTO_UPDATE=1
  export HOMEBREW_NO_INSTALL_FROM_API=1
  brew install xcodegen
  XCODEGEN="$(command -v xcodegen)"
fi

echo "ci_post_clone: using $("$XCODEGEN" --version 2>/dev/null | tr '\n' ' ')"

echo "ci_post_clone: running xcodegen generate in $WORKSPACE"
cd "$WORKSPACE"
"$XCODEGEN" generate

echo "ci_post_clone: done"
